import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from './redux/StoreProvider';
import LeftFrame from "./components/LeftFrame/LeftFrame";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Yellow Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        {/* <LeftFrame/> */}
        <body className={montserrat.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}
